http:
  private:
    port: "8081"

process:
  logs:
    defaultLimit: "200"
    maxLimit: "1000"
  source:
    maxRetries: "2"
    retryMillis: "1000"
  dispatch:
    maxRetries: "2"
    retryMillis: "1000"

sys:
  auth:
    clientIdHeader: "client_id"
    clientSecretHeader: "client_secret"
  anypoint:
    basePath: "/api/v1"
    logsPath: "/logs"
    responseTimeoutMillis: "10000"
  observability:
    basePath: "/api/v1"
    logsPath: "/logs"
    responseTimeoutMillis: "10000"

control:
  plane:
    basePath: "/api/v1"
    mockMode: "true"
    responseTimeoutMillis: "10000"
