http:
  private:
    port: "8081"

sys:
  auth:
    clientId: "01115d3f8c8c42c5b66bb585baca652d"
  anypoint:
    protocol: "HTTPS"
    host: "aip-mule-sys-anypoint-logs-api-app-test-wpx6rx.5sc6y6-4.usa-e2.cloudhub.io"
    port: "443"
  observability:
    protocol: "HTTPS"
    host: "aip-mule-sys-observability-logs-api-a-test-wpx6rx.5sc6y6-2.usa-e2.cloudhub.io"
    port: "443"
  controlPlane:
    protocol: "HTTPS"
    host: "aip-mule-sys-control-plane-api-app-test-wpx6rx.5sc6y6-4.usa-e2.cloudhub.io"
    port: "443"
    mockMode: "false"

# Autodiscovery configuration
api.id: "0"
