http:
  private:
    port: "8081"

sys:
  auth:
    clientId: "replace-uat-client-id"
  anypoint:
    protocol: "HTTPS"
    host: "replace-uat-anypoint-host"
    port: "443"
  observability:
    protocol: "HTTPS"
    host: "replace-uat-observability-host"
    port: "443"
  controlPlane:
    protocol: "HTTPS"
    host: "replace-uat-aip-mule-sys-control-plane-host"
    port: "443"
    mockMode: "false"

# Autodiscovery configuration
api.id: "0"
