test:
  replicas: "1"
  vCores: "0.1"
  runtimeVersion: "4.9.0"
  releaseChannel: "LTS"
  javaVersion: "17"
  clustered: "false"
  objectStoreV2: "true"
  lastMileSecurity: "false"
  forwardSslSession: "false"
  generateDefaultPublicUrl: "false"
  publicUrl: ""

uat:
  replicas: "1"
  vCores: "0.1"
  runtimeVersion: "4.9.0"
  releaseChannel: "LTS"
  javaVersion: "17"
  clustered: "false"
  objectStoreV2: "true"
  lastMileSecurity: "false"
  forwardSslSession: "false"
  generateDefaultPublicUrl: "false"
  publicUrl: ""

prod:
  replicas: "2"
  vCores: "0.2"
  runtimeVersion: "4.9.0"
  releaseChannel: "LTS"
  javaVersion: "17"
  clustered: "false"
  objectStoreV2: "true"
  lastMileSecurity: "false"
  forwardSslSession: "false"
  generateDefaultPublicUrl: "false"
  publicUrl: ""
